tasks:
  ## Example
    ## TASKID can be any alphanumeric string.
    # TASKID:
      ## The delay (in seconds) between pasting in schematics.
      ## Default: 300.
      # delay-seconds: 300
      # nodes:
        ## NODEID can be any alphanumeric string.
        # NODEID:
          ## World needs to be a valid and loaded World.
          # world: WORLD_NAME
          ## A list of X, Y, and Z coordinates where the schematic will be placed at. (Randomly chosen)
          # locations:
            # - 0 0 0
            # - 1 1 1
            # - 2 2 2
          ## A single X, Y, and Z coordinate.
          # safe-location: 0 0 0
          ## A list of schematics to paste for the node. (Randomly chosen)
          ## Any schematic here must exist inside WorldEdit/schematics or FastAsyncWorldEdit/schematics.
          # schematics:
            # - "SCHEMATIC_NAME.schem"
            # - "SCHEMATIC_NAME.schem"
            # - "SCHEMATIC_NAME.schem"
          ## Region must be a valid WorldGuard region in the World above.
          # region: REGION_NAME
          ## Must be a valid Material
          ## See: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
          # blocks-allowed:
            # - BLOCK_ID
            # - BLOCK_ID
            # - BLOCK_ID